# Generated by Django 5.2.2 on 2026-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn_app', '0002_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', help_text='Payment status: pending, paid, failed', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, null=True),
        ),
    ]
